[tool.black]
line-length = 100
target-version = ["py311"]
include = '\.py$'

[tool.ruff]
line-length = 100
target-version = "py311"
exclude = ["frontend", ".venv"]
select = ["E", "F", "I", "B", "W"]
ignore = ["E501"]

[tool.ruff.lint.isort]
known-first-party = ["ducky_logic", "main"]
